name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Publish'
    runs-on: ubuntu-latest
    steps:
       # Checkout updated source code
      - uses: actions/checkout@v4
        name: Checkout Code

      - name: Tag
        id: autotagger
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # If the new version/tag is a pre-release (i.e. 1.0.0-beta.1), create
        # an environment variable indicating it is a prerelease.
      - name: Pre-release
        if: steps.autotagger.outputs.tagname != ''
        run: |
          if [[ "${{ steps.autotagger.output.version }}" == *"-"* ]]; then echo "::set-env IS_PRERELEASE=true";else echo "::set-env IS_PRERELEASE=''";fi

      - name: Release
        id: create_release
        if: steps.autotagger.outputs.tagname != ''
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.autotagger.outputs.tagname }}
          release_name: ${{ steps.autotagger.outputs.tagname }}
          body: ${{ steps.autotagger.outputs.tagmessage }}
          draft: false
          prerelease: env.IS_PRERELEASE != ''

      - name: Setup Go
        if: steps.create_release.outputs.id != ''
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0' # The Go version to download (if necessary) and use.

      - run: go version
        if: steps.create_release.outputs.id != ''

      - uses: actions/setup-node@v3
        if: steps.create_release.outputs.id != ''
        name: Setup Node.js
        with:
          node-version: lts/*

      - name: Install Quikdev Go Tool
        run: npm i -g @quikdev/go
        if: steps.create_release.outputs.id != ''

      - name: Build Windows
        if: steps.create_release.outputs.id != ''
        run: mkdir -p && qgo build -o /dist/windows/dh-util.exe
        env:
          GOOS: windows

      - name: Build macOS
        if: steps.create_release.outputs.id != ''
        run: mkdir -p /dist/darwin && qgo build -o /dist/darwin/dh-util
        env:
          GOOS: darwin

      - name: Build Linux
        if: steps.create_release.outputs.id != ''
        run: mkdir -p /dist/linux && qgo build -o /dist/linux/dh-util
        env:
          GOOS: linux

      - name: Temp
        run: ls -l /dist/darwin/windows && ls -l /dist/darwin && ls -l /dist/linux

      - name: Rollback Release
        if: failure() && steps.create_release.outputs.id != ''
        uses: author/action-rollback@stable
        with:
          tag: ${{ steps.autotagger.outputs.tagname }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
